routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/* Dashboard */
Route::get('rkb', 'front\frontController@index')->name('rkb');
Route::get('profile', 'front\profileController@index')->name('profile');
Route::get('gallerykegiatan', 'front\GalleryController@index');
Route::get('struktur', 'front\StrukturController@index')->name('struktur');
Route::get('kegiatanrutin/{id}', 'front\KegiatanController@info')->name('info');

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('profil', 'Admin\profilController');
    Route::resource('gallery', 'Admin\galleryController');
    Route::resource('kegiatan', 'Admin\kegiatanController');
    Route::resource('fotostruktur', 'Admin\fotoStrukturController');
    Route::resource('detailstruktur', 'Admin\detailStrukturController');
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['judul', 'foto'];
}

app/Http/Controllers/Admin/galleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Gallery;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\createGalleryRequest;
use App\Http\Requests\Admin\updateGalleryRequest;
use Illuminate\Http\Request;

class galleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Gallery::paginate(10);
        return view('Admin.Gallery.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(createGalleryRequest $request)
    {
        $data = $request->all();
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'gallery' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/gallery/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        Gallery::create($data);
        toast('Data Gallery Berhasil Di Tambah','success');
        return redirect()->route('gallery.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        return view('Admin.Gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateGalleryRequest $request, Gallery $gallery)
    {
        $data = $request->all();
        $data['foto'] = $gallery->foto;
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'gallery' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/gallery/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        $gallery->update($data);
        toast('Data Gallery Berhasil Di Update','success');
        return redirect()->route('gallery.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Gallery $gallery)
    {
        $gallery->delete();
        toast('Data Gallery Berhasil Di Hapus','error');
        return redirect()->route('gallery.index');
    }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('gallery.allGallery');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function show(Gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Gallery $gallery)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy(Gallery $gallery)
    {
        //
    }
}

app/Http/Controllers/front/GalleryController.php
<?php

namespace App\Http\Controllers\front;

use App\Gallery;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function index()
    {
        $galeri = Gallery::all();
        return view('front.gallery.allGallery', compact('galeri'));
    }
}

resources/views/Admin/Gallery/create.blade.php
@extends('layouts.purple')

@section('content')
  {{-- <div class="page-header">
    <h3 class="page-title">
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
        <i class="mdi mdi-account-box"></i>
      </span> Edit Profile
    </h3>
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
          <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
        </li>
      </ul>
    </nav>
  </div> --}}
  <div class="row">
      <div class="col-md-12">
        @foreach ($errors->all() as $error)
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ $error }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endforeach
      </div>
  </div>
  <div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Add Gallery</h4> <br>
            <form class="forms-sample" action="{{ route('gallery.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
              <div class="form-group">
                <label for="exampleInputEmail3">Judul</label>
                <input type="text" class="form-control" name="judul" placeholder="Input Judul Foto" value="{{ old('judul') }}">
              </div>    
              <div class="form-group">
                <label>Foto</label>
                <input type="file" name="foto" class="file-upload-default">
                <div class="input-group col-xs-12">
                  <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">
                  <span class="input-group-append">
                    <button class="file-upload-browse btn btn-gradient-secondary" type="button">Upload</button>
                  </span>
                </div>
                {{-- <div class="form-group mt-2" style="max-width: 20rem;">
                    <img src="{{ asset($profil->foto) }}" class="img-fluid" alt="">
                </div> --}}
              </div>
              
              <button type="submit" class="btn btn-gradient-info mr-2">Submit</button>
              <button class="btn btn-light">Cancel</button>
            </form>
          </div>
        </div>
      </div>
  </div>
  
    
@endsection

resources/views/Admin/Gallery/edit.blade.php
@extends('layouts.purple')

@section('content')
  {{-- <div class="page-header">
    <h3 class="page-title">
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
        <i class="mdi mdi-account-box"></i>
      </span> Edit Profile
    </h3>
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
          <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
        </li>
      </ul>
    </nav>
  </div> --}}
  <div class="row">
      <div class="col-md-12">
        @foreach ($errors->all() as $error)
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ $error }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endforeach
      </div>
  </div>
  <div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Edit Gallery</h4> <br>
            <form class="forms-sample" action="{{ route('gallery.update', $gallery) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
              <div class="form-group">
                <label for="exampleInputEmail3">Judul</label>
                <input type="text" class="form-control" name="judul" placeholder="Input Judul Foto" value="{{ old('judul', $gallery->judul) }}">
              </div>    
              <div class="form-group">
                <label>Foto</label>
                <input type="file" name="foto" class="file-upload-default">
                <div class="input-group col-xs-12">
                  <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">
                  <span class="input-group-append">
                    <button class="file-upload-browse btn btn-gradient-secondary" type="button">Upload</button>
                  </span>
                </div>
                <div class="form-group mt-2" style="max-width: 20rem;">
                    <img src="{{ asset($gallery->foto) }}" class="img-fluid" alt="">
                </div>
              </div>
              
              <button type="submit" class="btn btn-gradient-info mr-2">Submit</button>
              <button class="btn btn-light">Cancel</button>
            </form>
          </div>
        </div>
      </div>
  </div>
  
    
@endsection

resources/views/Admin/Gallery/index.blade.php
@extends('layouts.purple')

@section('content')
<div class="row" id="proBanner">
    {{-- <div class="col-12">
      <span class="d-flex align-items-center purchase-popup">
        <p>Get tons of UI components, Plugins, multiple layouts, 20+ sample pages, and more!</p>
        <a href="https://www.bootstrapdash.com/product/purple-bootstrap-admin-template?utm_source=organic&utm_medium=banner&utm_campaign=free-preview" target="_blank" class="btn download-button purchase-button ml-auto">Upgrade To Pro</a>
        <i class="mdi mdi-close" id="bannerClose"></i>
      </span>
    </div> --}}
  </div>
  {{-- <div class="page-header">
    <h3 class="page-title">
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
        <i class="mdi mdi-account-box"></i>
      </span> Gallery
    </h3>
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
          <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
        </li>
      </ul>
    </nav>
  </div> --}}

  <div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h4 class="card-title">Gallery RKB</h4>
                </div>
                <div class="col-md-6 text-right">
                    <a href="{{ route('gallery.create') }}" class="btn btn-gradient-primary btn-sm">Add Data <i class="mdi mdi-loupe btn-icon-append"></i></a>
                </div>
            </div>
            <table class="table table-hover text-center">
              <thead>
                <tr>
                  <th> No </th>
                  <th> Judul </th>
                  <th> Foto </th>
                  <th> Aksi </th>
                </tr>
              </thead>
              <tbody>
                  @forelse ($data as $item => $gallery)
                  <tr>
                    <td class="py-1">
                        {{ $data->firstItem() + $item }}
                    </td>
                    <td> {{ $gallery->judul }} </td>
                    <td> <img src="{{ asset($gallery->foto) }}" style="border-radius: 0; width: 150px; height: 100px;" alt=""> </td>
                    <td>
                      <form method="POST" action="{{ route('gallery.destroy', $gallery) }}" onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                        @method('DELETE')
                        @csrf
                        <a class="btn btn-gradient-warning btn-sm" href="{{ route('gallery.edit', $gallery) }}"><i class="mdi mdi-file-check btn-icon-append"></i></a>
                        {{-- <a class="btn btn-icon btn-success" href="{{ route('gallery.show', $gallery) }}"><i class="far fa-eye"></i></a> --}}
                        <button class="btn btn-gradient-danger btn-sm"><i class="mdi mdi-delete"></i></button>
                </form>
                    </td>
                  </tr>
                  @empty
                      <tr>
                        <td colspan="4">Data Masih Kosong</td>
                      </tr>
                  @endforelse
                
              </tbody>
            </table>
          </div>
          {{ $data->links() }}
        </div>
      </div>
      
  </div>
    
@endsection