routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/* Dashboard */
Route::get('rkb', 'front\frontController@index')->name('rkb');
Route::get('profile', 'front\profileController@index')->name('profile');
Route::get('gallerykegiatan', 'front\GalleryController@index');
Route::get('struktur', 'front\StrukturController@index')->name('struktur');
Route::get('kegiatanrutin/{id}', 'front\KegiatanController@info')->name('info');

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('profil', 'Admin\profilController');
    Route::resource('gallery', 'Admin\galleryController');
    Route::resource('kegiatan', 'Admin\kegiatanController');
    Route::resource('fotostruktur', 'Admin\fotoStrukturController');
    Route::resource('detailstruktur', 'Admin\detailStrukturController');
});

app/Struktur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Struktur extends Model
{
    //
}

app/Http/Controllers/StrukturController.php
<?php

namespace App\Http\Controllers;

use App\Struktur;
use Illuminate\Http\Request;

class StrukturController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('struktur.struktur');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Struktur  $struktur
     * @return \Illuminate\Http\Response
     */
    public function show(Struktur $struktur)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Struktur  $struktur
     * @return \Illuminate\Http\Response
     */
    public function edit(Struktur $struktur)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Struktur  $struktur
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Struktur $struktur)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Struktur  $struktur
     * @return \Illuminate\Http\Response
     */
    public function destroy(Struktur $struktur)
    {
        //
    }
}

app/Http/Controllers/front/StrukturController.php
<?php

namespace App\Http\Controllers\front;

use App\DetailStruktur;
use App\FotoStruktur;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class StrukturController extends Controller
{
    public function index()
    {
        $struk = DetailStruktur::all();
        $fotostruk = FotoStruktur::first();
        return view('front.struktur.struktur', compact('struk', 'fotostruk'));
    }
}

resources/views/Admin/Struktur/edit.blade.php
@extends('layouts.purple')

@section('content')
  {{-- <div class="page-header">
    <h3 class="page-title">
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
        <i class="mdi mdi-account-box"></i>
      </span> Edit Profile
    </h3>
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
          <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
        </li>
      </ul>
    </nav>
  </div> --}}
  <div class="row">
      <div class="col-md-12">
        @foreach ($errors->all() as $error)
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ $error }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        @endforeach
      </div>
  </div>
  <div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Edit Foto Struktur</h4> <br>
            <form class="forms-sample" action="{{ route('fotostruktur.update', $fotostruktur) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')    
              <div class="form-group">
                <label>Foto</label>
                <input type="file" name="foto" class="file-upload-default">
                <div class="input-group col-xs-12">
                  <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">
                  <span class="input-group-append">
                    <button class="file-upload-browse btn btn-gradient-secondary" type="button">Upload</button>
                  </span>
                </div>
                <div class="form-group mt-2" style="max-width: 20rem;">
                    <img src="{{ asset($fotostruktur->foto) }}" class="img-fluid" alt="">
                </div>
              </div>
              
              <button type="submit" class="btn btn-gradient-info mr-2">Submit</button>
              <button class="btn btn-light">Cancel</button>
            </form>
          </div>
        </div>
      </div>
  </div>
  
    
@endsection

resources/views/Admin/Struktur/index.blade.php
@extends('layouts.purple')

@section('content')
  <div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h4 class="card-title">Foto Struktur</h4>
                </div>
            </div>
            <table class="table table-hover text-center">
              <thead>
                <tr>
                  <th> No </th>
                  <th> Foto </th>
                  <th> Aksi </th>
                </tr>
              </thead>
              <tbody>
                 <tr>
                     <td>1</td>
                     <td>
                        <img src="{{ asset($fotostruktur->foto) }}" style="border-radius: 0; width: 150px; height: 100px;" alt="">
                     </td>
                     <td>
                        <a class="btn btn-gradient-warning btn-sm" href="{{ route('fotostruktur.edit', $fotostruktur) }}"><i class="mdi mdi-file-check btn-icon-append"></i></a>
                     </td>
                 </tr>
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
      
  </div>
    
@endsection